#!/bin/bash -e
# Must be run from the root directory of the repository
# Activate venv
source venv/bin/activate
# Add repo to PATH
PYTHONPATH=$(pwd):$PYTHONPATH
# Launch app
exec gunicorn -w 1 -b unix:web.sock --log-file - --access-logfile - website:app
