#!/bin/bash -e
# Requires environment variable $WEBSITE_DIR set
# Activate venv
source $WEBSITE_DIR/venv/bin/activate
# Add to PATH
PYTHONPATH=$WEBSITE_DIR:$PYTHONPATH
# Launch app
exec gunicorn -w 1 -b unix:web.sock --log-file - --access-logfile - website:app
