name: Deploy to server

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOYMENT_SERVER_PUBLIC_KEY" > ~/.ssh/deployment_server.pub
          chmod 600 ~/.ssh/deployment_server.pub
          echo "Host deployment_server
                  HostName $DEPLOYMENT_SERVER_HOST
                  User $DEPLOYMENT_SERVER_USER
                  IdentityFile ~/.ssh/deployment_server.pub
                  StrictHostKeyChecking no" > ~/.ssh/config
        env:
          DEPLOYMENT_SERVER_PUBLIC_KEY: ${{ secrets.DEPLOYMENT_SERVER_PUBLIC_KEY }}
          DEPLOYMENT_SERVER_HOST: ${{ secrets.DEPLOYMENT_SERVER_HOST }}
          DEPLOYMENT_SERVER_USER: ${{ secrets.DEPLOYMENT_SERVER_USER }}
          
      - name: Stop running application
        run: ssh deployment_server 'systemctl --user stop website'
        
      - name: Pull from repo
        run: ssh deployment_server "cd $REPO_DIR; git reset --hard; git pull"
        env:
          REPO_DIR: ${{ secrets.REPO_DIR }}
      
      - name: Restart application
        if: ${{ always() }}
        run: ssh deployment_server 'systemctl --user start website'
        
